### ISSUE TITLE
Question3 and Question13 disagree on "pypercent format ends with(out) newline"

### ISSUE THREAD

**Issue by Kehrlann** [ue12-p21/python-advanced-evaluation#8]
The fact that formatter conversions should ends with newline or not is really complicated and does not render well in unit tests.

As a side note, q3 says "pypercent must end with a single newline", and q13 says "when writing to a file, strip the last line". That may be confusing to students.

Should we call `.strip()` on function outputs in the tests? (caveat: `test_to_starboard_html` needs more work)

---

Test for q3:

```python
class Question3(unittest.TestCase):
    def test_to_percent_hello_world(self):
        ipynb = load_ipynb("samples/hello-world.ipynb")
        self.assertEqual(
            r"""# %% [markdown]
# Hello world!
# ============
# Print `Hello world!`:

# %%
print("Hello world!")

# %% [markdown]
# Goodbye! 👋
""",
            to_percent(ipynb),
        )
```

test for q13:

```python
class Question13(unittest.TestCase):
    def test_py_percent_serializer(self):
            nb = Notebook.from_file("samples/hello-world.ipynb")
            ppp = PyPercentSerializer(nb)
            self.assertEqual(r"""# %% [markdown]
# Hello world!
# ============
# Print `Hello world!`:

# %%
print("Hello world!")

# %% [markdown]
# Goodbye! 👋"""
            , ppp.to_py_percent())
```

**Comment by Kehrlann** [comment]
tagging @ushu @parmentelat

**Comment by parmentelat** [comment]
my take on this is, we should accept **both file termination policies as correct** - just like what your average tool does

plus, selecting only one of the 2 at this late point would mean some students, who have their code pass already, may need to tweak their code, and that's not reasonable imho

**Comment by parmentelat** [comment]
in this PR I just remove all trailing newlines before comparing - with a reference string that has no trailing newline, of course
so any number of trailing newlines would be deemed OK
I did check for other occurrences(of questions where the test needed the fix), but did not spot any
